tap "homebrew/cask"
cask_args appdir: "/Applications"

brew "imagemagick"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "authy"
cask "postman"
cask "adoptopenjdk"
cask "dbeaver-community"

whalebrew "whalebrew/wget"